#!/bin/bash
# Script zur Integration eines openSUSE Clients in eine invis-Server Active-
# Directory Domaene
# (c) 2015 Stefan Schaefer -- invis-server.org
# License GPLv3
# Questions: info@invis-server.org

# Dieses Script führt alle zur Installation eines invis Servers AD notwendigen 
# Konfigurationsschritte aus.
# Das Script sine nutzt /var/lib/sine als Arbeitsverzeichnis, hier sind von sine
# verwendete Kontroll-, Variablen- und Protokolldateien zu finden.

# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 

# Funktionen
# Werte aus Konfigurationsdatendatei extrahieren
getconfdata() {
    cat $setupdir/invis_confdata |grep "$1:" | cut -d ":" -f $2
}

# Konfigurationsparameter tauschen
changevalues() {
    # Arg1 = Pfad, Arg2 = Datei, Arg3 = sed String
    cat $1/$2|sed "s%$3%g" > $1/$2.new
    mv $1/$2.new $1/$2
}

# Strings in Kleinschreibung umwandeln
tolower() {
    echo $1 | tr [:upper:] [:lower:]
}

# Strings in Kleinschreibung umwandeln
toupper() {
    echo $1 | tr [:lower:] [:upper:]
}

# Domaene abfragen
echo -e "Achtung: Dieses Script ist ausschließlich für openSUSE Clients gedacht!\n"
sleep 3
read -p "Geben Sie bitte den Namen Ihrer Domäne in DNS Schreibweise ein (Bsp.: example.loc): " reqdnsdomain

# Unterschiedliche Schreibweisen generieren
dotcount=`echo -n "$reqdnsdomain" | sed -e 's/[^.]//g' | wc -m`

dnsdomain=`tolower $reqdnsdomain`
krbrealm=`toupper $dnsdomain`

if (( $dotcount == 1 )); then
    netbiosdomain=`echo $krbrealm | cut -d "." -f1`
else
    netbiosdomain=`echo $krbrealm | cut -d "." -f1-$dotcount`
fi

# spins:invis:common Repository hinzufuegen
suseversion=`cat /etc/SuSE-release | grep VERSION | tr -d " " | cut -d "=" -f2`
zypper ar -f http://download.opensuse.org/repositories/spins:/invis:/common/openSUSE_$suseversion/spins:invis:common.repo
zypper --gpg-auto-import-keys ref

# Software installieren
zypper -n rm -n nscd
zypper -n in -n sssd sssd-ad sssd-tools cyrus-sasl-gssapi
zypper -n in -n --force-resolution --from spins_invis_common krb5-client

# Dateien sichern und kopieren
mv /etc/samba/smb.conf /etc/samba/smb.conf.setupsafe
if [[ -f /etc/sssd/sssd.conf ]]; then
    mv /etc/sssd/sssd.conf /etc/sssd/sssd.conf.setupsafe
fi
mv /etc/krb5.conf /etc/krb5.conf.setupsafe 
mv /etc/nsswitch.conf /etc/nsswitch.conf.setupsafe 

# Neue Konfigurationsdateien kopieren und anpassen
cp $PWD/files/krb5.conf /etc
cp $PWD/files/sssd.conf /etc/sssd
cp $PWD/files/smb.conf /etc/samba
cp $PWD/files/nsswitch.conf /etc

# Samba
path="/etc/samba"
modfile="smb.conf"

changestrings="INVIS-NET.LOC%$krbrealm"
changevalues $path $modfile "$changestrings"

changestrings="INVIS-NET%$netbiosdomain"
changevalues $path $modfile "$changestrings"

# Kerberos
path="/etc"
modfile="krb5.conf"

changestrings="INVIS-NET.LOC%$krbrealm"
changevalues $path $modfile "$changestrings"

# sssd
path="/etc/sssd/"
modfile="sssd.conf"

changestrings="invis-net.loc%$dnsdomain"
changevalues $path $modfile "$changestrings"

chown root.root "$path/$modfile"
chmod 0600 "$path/$modfile"


# Domaenenbeitritt durchfueren
# Bugfix, das folgende Verzeichnis fehlt
mkdir -p "/run/user/0/krb5cc"

echo -e "Sie benötigen jetzt das Passwort des Domänenadministrators.\n"

kinit Administrator@$krbrealm
net join -k

# Eventuell vorhandenen SSS Cache vollstaendig loeschen und sssd starten
$PWD/delssscache

# SSSD in Autostart integrieren.
systemctl enable sssd.service

# PAM Konfigurieren -> SSSD Modul aktivieren
pam-config --add --sss

## Jetzt noch die NFS Freigaben einhaengen
pdc=`dig SRV _ldap._tcp.$dnsdomain +short |cut -d " " -f4`
pdc=`echo "${pdc%?}"`

# Mount Verzeichnis anlegen
mkdir /mnt/invis

echo "$pdc:/home /home nfs4 defaults 0 0" >> /etc/fstab
echo "$pdc:/shares /mnt/invis/shares nfs4 defaults 0 0" >> /etc/fstab

# Alles mounten, was nicht gemountet ist.
mount -a
